name: Test on Windows

on:
  push:
    branches: [ "master", "tests" ]
  pull_request:
    branches: [ "master", "tests" ]

jobs:
  test:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up PostGIS
        run: |
          
          # Install PostGIS (PostgreSQL comes on the GitHub Actions runner by default but lacks PostGIS control files and dependencies) 
          Invoke-WebRequest -Uri "http://download.osgeo.org/postgis/windows/pg14/postgis-bundle-pg14x64-setup-3.4.1-1.exe" -OutFile "postgis-installer.exe"
          Start-Process "postgis-installer.exe" -ArgumentList "/S /D=C:\Program Files\PostgreSQL\14" -Wait -NoNewWindow
          & "C:\Program Files\PostgreSQL\14\bin\pg_ctl.exe" -D "C:\Program Files\PostgreSQL\14\data" start
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -c "CREATE DATABASE geodb;"
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -c "CREATE USER geodb_user WITH ENCRYPTED PASSWORD 'geodb_pass';"
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE geodb TO geodb_user;"
          & "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -d geodb -c "CREATE EXTENSION postgis;"

      - name: Set up Tomcat/GeoServer
        run: |
          
          # Configure firewall to allow connectiosn to localhost port 8080 (might not be necessary)
          netsh advfirewall firewall add rule name="Allow Localhost 8080" dir=in action=allow protocol=TCP localport=8080
          netsh advfirewall firewall show rule name="Allow Localhost 8080"
          
          # Download and install Apache Tomcat (need version 9 because the JRE on the GitHub Actions runner is incompatible with 10+)
          curl -L https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88-windows-x64.zip -o tomcat.zip
          Expand-Archive -Path tomcat.zip -DestinationPath "C:\"
          $directory = Get-ChildItem -Path "C:\" -Directory | Where-Object { $_.Name -like "*apache-tomcat*" } | Select-Object -First 1
          if ($directory) { Rename-Item -Path $directory.FullName -NewName "Tomcat" }
          dir C:\Tomcat
          
          # Download and install Geoserver, then move it to the Tomcat directory
          curl -L https://sourceforge.net/projects/geoserver/files/GeoServer/2.25.0/geoserver-2.25.0-war.zip/download -o geoserver.zip
          Expand-Archive -Path geoserver.zip -DestinationPath "C:\GeoServer"
          cp C:\GeoServer\geoserver.war C:\Tomcat\webapps\geoserver.war
          dir C:\Tomcat\webapps
          
          # Set env vars for Tomcat and run it (it takes a little while, so wait 30 seconds after)
          $env:CATALINA_BASE = "C:\Tomcat"
          $env:CATALINA_HOME = "C:\Tomcat"
          $env:CATALINA_TMPDIR = "C:\Tomcat\temp"
          C:\Tomcat\bin\startup.bat
          Start-Sleep -Seconds 30
          Get-NetTCPConnection | Where-Object State -eq 'Listen' | ForEach-Object { $Process = Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue; if ($Process) { [PSCustomObject]@{ProcessName = $Process.Name; PID = $Process.Id; Port = $_.LocalPort; IPAddress = $_.LocalAddress} } } | Format-Table -AutoSize
          
          # Verify Something is on port 8080
          Get-NetTCPConnection | Where-Object { $_.LocalPort -eq 8080 }
          $response = Invoke-WebRequest -Uri "http://localhost:8080"
          Write-Output $response.Content
          
          dir C:\Tomcat\logs
          Get-Content C:\Tomcat\logs\catalina.2024-05-04.log -Tail 100 -Wait
          Get-Content C:\Tomcat\logs\localhost.2024-05-04.log -Tail 100 -Wait
          
          $response = Invoke-WebRequest -Uri "http://localhost:8080/geoserver"
          Write-Output $response.Content

        shell: pwsh

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Miniconda
        run: |
          curl -O https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Windows-x86_64.exe
          Start-Process -FilePath "Miniconda3-py39_4.10.3-Windows-x86_64.exe" -ArgumentList '/InstallationType=JustMe /RegisterPython=0 /S /D="%UserProfile%\Miniconda3"' -Wait -NoNewWindow
          & "$env:UserProfile\Miniconda3\Scripts\conda" init powershell
        shell: pwsh

      - name: Configure Conda environment
        run: |
          $env:PATH = "$env:UserProfile\Miniconda3;$env:UserProfile\Miniconda3\Scripts;$env:UserProfile\Miniconda3\Library\bin;$env:PATH"
          conda update conda -y
          conda create -n geospatial python=3.10 -y
          conda activate geospatial
          conda install -c conda-forge gdal>=3.4.1 -y
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
        shell: pwsh

      - name: Run pytest
        run: |
          set DB_HOST=localhost
          conda activate geospatial
          pytest ./tests
