name: Test on Linux (Ubuntu)

on:
  push:
    branches: [ "master", "tests" ]
  pull_request:
    branches: [ "master", "tests" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL==`gdal-config --version` 
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Test with pytest
      run: |
        export DB_HOST=postgis
        docker compose -f tests/docker-compose.yaml up -d
        sleep 60  # Geoserver takes quite a long time to boot up and there is no healthcheck
        pytest ./tests
